export type University = { rank: number; university: string; program: string; city: string; state: string; deadline: string; fee: number; gre: 'Not required' | 'Optional' | 'Check program'; funding: string; programUrl: string; note: string }
type Seed = [string, string, string, string, number?, University['gre']?]
const seeds: Seed[] = [
['Massachusetts Institute of Technology','Cambridge','MA','https://www.eecs.mit.edu/academics/graduate-programs/admission-process/',75,'Not required'],
['Carnegie Mellon University','Pittsburgh','PA','https://www.cs.cmu.edu/academics/graduate-admissions',100,'Optional'],
['Stanford University','Stanford','CA','https://www.cs.stanford.edu/admissions/graduate-application-checklists',125,'Not required'],
['University of California, Berkeley','Berkeley','CA','https://eecs.berkeley.edu/academics/graduate/research-programs/admissions/',155,'Not required'],
['University of Illinois Urbana-Champaign','Urbana','IL','https://cs.illinois.edu/admissions/graduate',90,'Not required'],
['Georgia Institute of Technology','Atlanta','GA','https://www.cc.gatech.edu/degree-programs/phd-computer-science',105,'Optional'],
['University of Washington','Seattle','WA','https://www.cs.washington.edu/academics/phd/admissions',90,'Not required'],
['Cornell University','Ithaca','NY','https://www.cs.cornell.edu/phd/admissions',105,'Not required'],
['Princeton University','Princeton','NJ','https://www.cs.princeton.edu/grad/admissions',75,'Not required'],
['University of Michigan','Ann Arbor','MI','https://cse.engin.umich.edu/academics/graduate/admissions/',90,'Optional'],
['University of Texas at Austin','Austin','TX','https://www.cs.utexas.edu/graduate-program/prospective-students',90,'Optional'],
['University of California, San Diego','La Jolla','CA','https://cse.ucsd.edu/graduate/graduate-admissions',155,'Not required'],
['Columbia University','New York','NY','https://www.cs.columbia.edu/education/phd/admissions/',85,'Optional'],
['University of California, Los Angeles','Los Angeles','CA','https://www.cs.ucla.edu/graduate-admission/',155,'Optional'],
['University of Wisconsin–Madison','Madison','WI','https://www.cs.wisc.edu/graduate/admissions/',75,'Not required'],
['Harvard University','Cambridge','MA','https://seas.harvard.edu/computer-science/graduate-program',105,'Optional'],
['University of Maryland, College Park','College Park','MD','https://www.cs.umd.edu/grad/catalog/admission',75,'Optional'],
['University of Pennsylvania','Philadelphia','PA','https://www.cis.upenn.edu/graduate/how-to-apply/',90,'Not required'],
['Purdue University','West Lafayette','IN','https://www.cs.purdue.edu/graduate/admission/index.html',75,'Optional'],
['University of Southern California','Los Angeles','CA','https://www.cs.usc.edu/academic-programs/graduate-programs/',105,'Optional'],
['Yale University','New Haven','CT','https://cpsc.yale.edu/academics/graduate-program/applying-yale',105,'Not required'],
['University of Massachusetts Amherst','Amherst','MA','https://www.cics.umass.edu/admissions/application-instructions',85,'Optional'],
['Johns Hopkins University','Baltimore','MD','https://www.cs.jhu.edu/academic-programs/graduate-studies/phd-program/',75,'Optional'],
['Duke University','Durham','NC','https://cs.duke.edu/graduate/phd',95,'Optional'],
['Rice University','Houston','TX','https://csweb.rice.edu/academics/graduate-programs/admission',85,'Not required'],
['University of North Carolina at Chapel Hill','Chapel Hill','NC','https://cs.unc.edu/graduate/admissions/',95,'Optional'],
['Brown University','Providence','RI','https://cs.brown.edu/degrees/doctoral/applications/',75,'Not required'],
['Northwestern University','Evanston','IL','https://www.mccormick.northwestern.edu/computer-science/academics/graduate/phd/',95,'Optional'],
['New York University','New York','NY','https://cs.nyu.edu/home/phd/admission.html',110,'Optional'],
['University of California, Irvine','Irvine','CA','https://ics.uci.edu/admissions/graduate-admissions/',155,'Optional'],
['University of Chicago','Chicago','IL','https://cs.uchicago.edu/academics/phd/admissions/',90,'Optional'],
['Northeastern University','Boston','MA','https://www.khoury.northeastern.edu/apply/phd-apply/',100,'Optional'],
['University of Virginia','Charlottesville','VA','https://engineering.virginia.edu/department/computer-science/academics/graduate-programs/admissions',85,'Optional'],
['Pennsylvania State University','University Park','PA','https://www.eecs.psu.edu/students/graduate/Admissions.aspx',65,'Optional'],
['University of California, Santa Barbara','Santa Barbara','CA','https://cs.ucsb.edu/education/graduate/prospective-students',155,'Optional'],
['Texas A&M University','College Station','TX','https://engineering.tamu.edu/cse/academics/degrees/graduate/admissions.html',90,'Optional'],
['Ohio State University','Columbus','OH','https://cse.osu.edu/prospective-students/graduate/admissions',60,'Optional'],
['University of Minnesota Twin Cities','Minneapolis','MN','https://cse.umn.edu/cs/graduate-admissions',95,'Optional'],
['Virginia Tech','Blacksburg','VA','https://cs.vt.edu/Graduate/Prospective.html',75,'Optional'],
['Rutgers University–New Brunswick','Piscataway','NJ','https://www.cs.rutgers.edu/academics/graduate/admission',70,'Optional'],
['University of Colorado Boulder','Boulder','CO','https://www.colorado.edu/cs/academics/graduate-programs/admissions',80,'Optional'],
['University of California, Davis','Davis','CA','https://cs.ucdavis.edu/graduate/prospective-graduate-students',155,'Optional'],
['Washington University in St. Louis','St. Louis','MO','https://engineering.wustl.edu/academics/programs/computer-science-engineering/graduate-admissions.html',75,'Optional'],
['Stony Brook University','Stony Brook','NY','https://www.cs.stonybrook.edu/admissions/Graduate-Program',100,'Optional'],
['University of Utah','Salt Lake City','UT','https://www.cs.utah.edu/graduate/admissions/',65,'Optional'],
['University of Arizona','Tucson','AZ','https://www.cs.arizona.edu/graduate/how-apply',90,'Optional'],
['University of Pittsburgh','Pittsburgh','PA','https://www.sci.pitt.edu/admissions/graduate-admissions',75,'Optional'],
['Boston University','Boston','MA','https://www.bu.edu/cs/masters-phd/admissions/',95,'Optional'],
['University of Florida','Gainesville','FL','https://www.cise.ufl.edu/admissions/graduate/',30,'Optional'],
['Arizona State University','Tempe','AZ','https://scai.engineering.asu.edu/graduate-computer-science/',115,'Optional'],
['North Carolina State University','Raleigh','NC','https://www.csc.ncsu.edu/academics/graduate/admissions.php',85,'Optional'],
['University of California, Riverside','Riverside','CA','https://www1.cs.ucr.edu/graduate/admissions',155,'Optional'],
['University at Buffalo, SUNY','Buffalo','NY','https://engineering.buffalo.edu/computer-science-engineering/graduate/admissions.html',85,'Optional'],
['University of Notre Dame','Notre Dame','IN','https://cse.nd.edu/graduate/admissions/',75,'Optional'],
['Rensselaer Polytechnic Institute','Troy','NY','https://science.rpi.edu/computer-science/programs/graduate',75,'Optional'],
['University of Rochester','Rochester','NY','https://www.cs.rochester.edu/graduate/admissions.html',60,'Optional'],
['Michigan State University','East Lansing','MI','https://engineering.msu.edu/about/departments/cse/graduate-programs',65,'Optional'],
['University of Delaware','Newark','DE','https://www.cis.udel.edu/graduate/apply/',75,'Optional'],
['Vanderbilt University','Nashville','TN','https://engineering.vanderbilt.edu/cs/graduate-programs/',95,'Optional'],
['University of Iowa','Iowa City','IA','https://cs.uiowa.edu/graduate-program',60,'Optional'],
['Iowa State University','Ames','IA','https://www.cs.iastate.edu/graduate-program',60,'Optional'],
['University of Oregon','Eugene','OR','https://cs.uoregon.edu/graduate-programs',90,'Optional'],
['Oregon State University','Corvallis','OR','https://engineering.oregonstate.edu/academics/programs/computer-science/graduate',85,'Optional'],
['University of Tennessee, Knoxville','Knoxville','TN','https://eecs.utk.edu/graduate/',60,'Optional'],
['University of Connecticut','Storrs','CT','https://www.cse.uconn.edu/graduate-studies/',80,'Optional'],
['George Mason University','Fairfax','VA','https://cs.gmu.edu/prospective-students/graduate-programs/',75,'Optional'],
['University of Central Florida','Orlando','FL','https://www.cs.ucf.edu/academics/graduate/',31,'Optional'],
['University of Illinois Chicago','Chicago','IL','https://cs.uic.edu/graduate/admissions/',70,'Optional'],
['Indiana University Bloomington','Bloomington','IN','https://luddy.indiana.edu/admissions/graduate/index.html',70,'Optional'],
['Tufts University','Medford','MA','https://engineering.tufts.edu/cs/graduate',85,'Optional'],
['University of California, Santa Cruz','Santa Cruz','CA','https://grad.soe.ucsc.edu/cse',155,'Optional'],
['George Washington University','Washington','DC','https://graduate.seas.gwu.edu/doctoral-programs',80,'Optional'],
['Case Western Reserve University','Cleveland','OH','https://engineering.case.edu/computer-and-data-sciences/academics/graduate-programs',50,'Optional'],
['University of Texas at Dallas','Richardson','TX','https://engineering.utdallas.edu/academics/graduate-majors/computer-science/',50,'Optional'],
['University of South Florida','Tampa','FL','https://www.usf.edu/engineering/cse/graduate/',30,'Optional'],
['University of Nebraska–Lincoln','Lincoln','NE','https://computing.unl.edu/graduate-programs/',50,'Optional'],
['University of Georgia','Athens','GA','https://www.cs.uga.edu/graduate-programs',75,'Optional'],
['Colorado State University','Fort Collins','CO','https://compsci.colostate.edu/graduate-study/',70,'Optional'],
['Drexel University','Philadelphia','PA','https://drexel.edu/cci/academics/graduate-programs/computer-science/',65,'Optional'],
['Syracuse University','Syracuse','NY','https://ecs.syracuse.edu/academics/electrical-engineering-and-computer-science/programs/computer-and-information-science-phd',75,'Optional'],
['Clemson University','Clemson','SC','https://www.clemson.edu/cecas/departments/computing/academics/graduate/',90,'Optional'],
['University of New Mexico','Albuquerque','NM','https://www.cs.unm.edu/graduate/',70,'Optional'],
['University of Kansas','Lawrence','KS','https://eecs.ku.edu/graduate-programs',65,'Optional'],
['University of Kentucky','Lexington','KY','https://cs.uky.edu/graduate',75,'Optional'],
['University of Maryland, Baltimore County','Baltimore','MD','https://www.csee.umbc.edu/graduate/computer-science/',50,'Optional'],
['New Jersey Institute of Technology','Newark','NJ','https://computing.njit.edu/graduate-programs',75,'Optional'],
['Worcester Polytechnic Institute','Worcester','MA','https://www.wpi.edu/academics/study/computer-science-phd',70,'Optional'],
['Stevens Institute of Technology','Hoboken','NJ','https://www.stevens.edu/program/computer-science-doctoral-program',60,'Optional'],
['University of Houston','Houston','TX','https://www.cs.uh.edu/graduate/',80,'Optional'],
['Florida State University','Tallahassee','FL','https://www.cs.fsu.edu/academics/graduate-programs/',30,'Optional'],
['University of North Texas','Denton','TX','https://computerscience.engineering.unt.edu/graduate',75,'Optional'],
['University of Texas at Arlington','Arlington','TX','https://www.uta.edu/academics/schools-colleges/engineering/academics/departments/cse/graduate',90,'Optional'],
['University of Alabama at Birmingham','Birmingham','AL','https://www.uab.edu/cas/computerscience/graduate',60,'Optional'],
['Wayne State University','Detroit','MI','https://engineering.wayne.edu/computer-science/graduate',50,'Optional'],
['University of Cincinnati','Cincinnati','OH','https://ceas.uc.edu/academics/departments/electrical-computer-engineering/degrees-programs/computer-science-graduate.html',80,'Optional'],
['Temple University','Philadelphia','PA','https://cis.temple.edu/academics/graduate-programs/',60,'Optional'],
['University of Oklahoma','Norman','OK','https://www.ou.edu/coe/cs/academics/graduate',100,'Optional'],
['University of South Carolina','Columbia','SC','https://sc.edu/study/colleges_schools/engineering_and_computing/academics/computer_science_and_engineering/',50,'Optional'],
['Louisiana State University','Baton Rouge','LA','https://www.lsu.edu/eng/cse/academics/graduate/',70,'Optional'],
['University of Arkansas','Fayetteville','AR','https://computer-science-and-computer-engineering.uark.edu/academics/graduate/',60,'Optional'],
]
const deadlineByRank=(rank:number)=>rank<=12?'2026-12-01':rank<=28?'2026-12-15':rank<=55?'2027-01-05':rank<=78?'2027-01-15':'2027-02-01'
export const universities: University[]=seeds.map((s,i)=>({rank:i+1,university:s[0],city:s[1],state:s[2],programUrl:s[3],fee:s[4]??75,gre:s[5]??'Check program',program:'PhD in Computer Science',deadline:deadlineByRank(i+1),funding:'Full funding is typical for admitted PhD students; confirm the guarantee and duration.',note:'Fall 2027 deadline is a planning estimate based on recent cycles. Verify when the university publishes the 2027 cycle.'}))
